version: "3.8"
services:
  web:
    build:
      context: ..
      dockerfile: docker-test/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/app/webapp
      - /home/app/webapp/node_modules
      - /home/app/webapp/dist
